/*
*** Eliminar tabla TBLVICTIMAS_PERSONA
*/
DROP TABLE dbo.tblsisben;
/*
** CREACION TABLA TBLVICTIMAS_PERSONA
*/
CREATE Table dbo.tblsisben(
    ID_BD_VIC INT not NULL,
    TIPO_DOCUMENTO NVARCHAR(20),
    DOCUMENTO NVARCHAR(50),
    NOMBRE_1 NVARCHAR(100),
    NOMBRE_2 NVARCHAR(100),
    APELLIDO_1 NVARCHAR(100),
    APELLIDO_2 NVARCHAR(100),
    FECHANACIMIENTO DATE,
    FECHA_NACIMIENTO DATE,
    NOM1_F NVARCHAR(100),
    NOM2_F NVARCHAR(100),
    APE1_F NVARCHAR(100),
    APE2_F NVARCHAR(100),
    PERSONA_DUPLICADA NVARCHAR(100),
    ESTADO NVARCHAR(100),
    IND_CRUCE_SISBEN_III NVARCHAR(100),
    COD_CRUCE_SISBEN_III NVARCHAR(100),
    ID_SISBEN_III NVARCHAR(100),
    PUNTAJE_SISBEN_III NVARCHAR(100),
    ID_HOGAR_SISBEN_III NVARCHAR(100),
    IND_CRUCE_SISBEN_IV NVARCHAR(100),
    COD_CRUCE_SISBEN_IV NVARCHAR(100),
    ID_SISBEN_IV NVARCHAR(100),
    COD_DEPTO_SISBEN_IV NVARCHAR(100),
    COD_MUNICIPIO_SISBEN_IV NVARCHAR(100),
    GRUPO_SISBEN_IV NVARCHAR(100),
    NIVEL_SISBEN_IV NVARCHAR(100),
    ID_HOGAR_SISBEN_IV NVARCHAR(100)

)

/*
** CREACION LLAVE PRIMARIA
*/
ALTER Table dbo.tblsisben ADD CONSTRAINT pk_bd_id PRIMARY KEY NONCLUSTERED ("ID_BD_VIC") NOT ENFORCED;

/*
** Inserción de datos
*/
INSERT INTO dbo.tblsisben
    ([ID_BD_VIC]
    ,[TIPO_DOCUMENTO]
    ,[DOCUMENTO]
    ,[NOMBRE_1]
    ,[NOMBRE_2]
    ,[APELLIDO_1]
    ,[APELLIDO_2]
    ,[FECHANACIMIENTO]
    ,[FECHA_NACIMIENTO]
    ,[NOM1_F]
    ,[NOM2_F]
    ,[APE1_F]
    ,[APE2_F]
    ,[PERSONA_DUPLICADA]
    ,[ESTADO]
    ,[IND_CRUCE_SISBEN_III]
    ,[COD_CRUCE_SISBEN_III]
    ,[ID_SISBEN_III]
    ,[PUNTAJE_SISBEN_III]
    ,[ID_HOGAR_SISBEN_III]
    ,[IND_CRUCE_SISBEN_IV]
    ,[COD_CRUCE_SISBEN_IV]
    ,[ID_SISBEN_IV]
    ,[COD_DEPTO_SISBEN_IV]
    ,[COD_MUNICIPIO_SISBEN_IV]
    ,[GRUPO_SISBEN_IV]
    ,[NIVEL_SISBEN_IV]
    ,[ID_HOGAR_SISBEN_IV])
SELECT  [ID_BD_VIC],[TIPO_DOCUMENTO],[DOCUMENTO],[NOMBRE_1],[NOMBRE_2],[APELLIDO_1],[APELLIDO_2]
        ,(CASE WHEN (ISDATE([FECHANACIMIENTO]) > 0) THEN CONVERT(DATE, [FECHANACIMIENTO]) ELSE CONVERT(DATE, '1900-01-01') END) as FECHANACIMIENTO
        ,(CASE WHEN (ISDATE([FECHA_NACIMIENTO]) > 0) THEN CONVERT(DATE, [FECHA_NACIMIENTO]) ELSE CONVERT(DATE, '1900-01-01') END) as FECHA_NACIMIENTO
        ,[NOM1_F],[NOM2_F],[APE1_F],[APE2_F],[PERSONA_DUPLICADA]
        ,[ESTADO],[IND_CRUCE_SISBEN_III],[COD_CRUCE_SISBEN_III],[ID_SISBEN_III],[PUNTAJE_SISBEN_III]
        ,[ID_HOGAR_SISBEN_III],[IND_CRUCE_SISBEN_IV],[COD_CRUCE_SISBEN_IV],[ID_SISBEN_IV],[COD_DEPTO_SISBEN_IV]
        ,[COD_MUNICIPIO_SISBEN_IV],[GRUPO_SISBEN_IV],[NIVEL_SISBEN_IV],[ID_HOGAR_SISBEN_IV]
 FROM [dbo].[sisben]

 /*
 ** Total de registros cargados en la tabla sisteban 9057733
 */
SELECT COUNT(ID_BD_VIC) FROM dbo.tblsisben;

/*
*** Eliminar tabla Sisben2
*/
DROP TABLE dbo.tblsisben2;

/*
** Crear tabla sisben2
*/

CREATE Table dbo.tblsisben2(
    ID_HOGAR_SISBEN_IV INT NOT NULL,
    IDE_NACIONAL NVARCHAR(1024),
    COD_DPTO NVARCHAR(1024),
    COD_MPIO NVARCHAR(1024),
    NUM_FICHA NVARCHAR(1024),
    IDE_HOGAR NVARCHAR(1024),
    COD_COMUNA NVARCHAR(1024),
    COD_CORREGIMIENTO NVARCHAR(1024),
    NOM_CORREGIMIENTO NVARCHAR(4000),
    COD_VEREDA NVARCHAR(1024),
    NOM_VEREDA NVARCHAR(4000),
    COD_BARRIO NVARCHAR(1024),
    NOM_BARRIO NVARCHAR(4000),
    DIR_VIVIENDA NVARCHAR(1024),
    FEC_INI_ENCUESTA DATE,
    FEC_FIN_ENCUESTA DATE,
    NUM_TEL_CONTACTO NVARCHAR(1024),
    PRI_NOMBRE NVARCHAR(1024),
    SEG_NOMBRE NVARCHAR(1024),
    PRI_APELLIDO NVARCHAR(1024),
    SEG_APELLIDO NVARCHAR(1024),
    TIP_PARENTESCO NVARCHAR(1024),
    TIP_DOCUMENTO NVARCHAR(1024),
    NUM_DOCUMENTO NVARCHAR(1024),
    FEC_NACIMIENTO DATE,
    SEXO_PERSONA NVARCHAR(1024),
    EDAD_CALCULADA NVARCHAR(1024),
    IND_GRUPO NVARCHAR(1024),
    IND_NIVEL NVARCHAR(1024),
    EDAD NVARCHAR(1024),
    NIV_EDUCATIVO NVARCHAR(1024),
    IND_DISCAP_VER NVARCHAR(4000),
    IND_DISCAP_OIR NVARCHAR(4000),
    IND_DISCAP_HABLAR NVARCHAR(4000),
    IND_DISCAP_MOVERSE NVARCHAR(4000),
    IND_DISCAP_BAÑARSE NVARCHAR(4000),
    IND_DISCAP_SALIR NVARCHAR(4000),
    IND_DISCAP_ENTENDER NVARCHAR(4000),
    IND_DISCAP_NINGUNA NVARCHAR(4000)

)

/*
** CREACION LLAVE PRIMARIA
*/
ALTER Table dbo.tblsisben2 ADD CONSTRAINT pk_id PRIMARY KEY NONCLUSTERED ("ID_HOGAR_SISBEN_IV") NOT ENFORCED;


/*
** Cargar información a la tabla 
*/

INSERT INTO dbo.tblsisben2(
    [ID_HOGAR_SISBEN_IV]
    ,[IDE_NACIONAL]
    ,[COD_DPTO]
    ,[COD_MPIO]
    ,[NUM_FICHA]
    ,[IDE_HOGAR]
    ,[COD_COMUNA]
    ,[COD_CORREGIMIENTO]
    ,[NOM_CORREGIMIENTO]
    ,[COD_VEREDA]
    ,[NOM_VEREDA]
    ,[COD_BARRIO]
    ,[NOM_BARRIO]
    ,[DIR_VIVIENDA]
    ,[FEC_INI_ENCUESTA]
    ,[FEC_FIN_ENCUESTA]
    ,[NUM_TEL_CONTACTO]
    ,[PRI_NOMBRE]
    ,[SEG_NOMBRE]
    ,[PRI_APELLIDO]
    ,[SEG_APELLIDO]
    ,[TIP_PARENTESCO]
    ,[TIP_DOCUMENTO]
    ,[NUM_DOCUMENTO]
    ,[FEC_NACIMIENTO]
    ,[SEXO_PERSONA]
    ,[EDAD_CALCULADA]
    ,[IND_GRUPO]
    ,[IND_NIVEL]
    ,[EDAD]
    ,[NIV_EDUCATIVO]
    ,[IND_DISCAP_VER]
    ,[IND_DISCAP_OIR]
    ,[IND_DISCAP_HABLAR]
    ,[IND_DISCAP_MOVERSE]
    ,[IND_DISCAP_BAÑARSE]
    ,[IND_DISCAP_SALIR]
    ,[IND_DISCAP_ENTENDER]
    ,[IND_DISCAP_NINGUNA])
 SELECT [ID_HOGAR_SISBEN_IV] ,[IDE_NACIONAL],[COD_DPTO],[COD_MPIO],[NUM_FICHA],[IDE_HOGAR],[COD_COMUNA],[COD_CORREGIMIENTO]
        ,[NOM_CORREGIMIENTO],[COD_VEREDA],[NOM_VEREDA],[COD_BARRIO],[NOM_BARRIO],[DIR_VIVIENDA]
        ,(CASE WHEN (ISDATE([FEC_INI_ENCUESTA]) > 0) THEN CONVERT(DATE, [FEC_INI_ENCUESTA]) ELSE CONVERT(DATE, '1900-01-01') END) as FEC_INI_ENCUESTA
        ,(CASE WHEN (ISDATE([FEC_FIN_ENCUESTA]) > 0) THEN CONVERT(DATE, [FEC_FIN_ENCUESTA]) ELSE CONVERT(DATE, '1900-01-01') END) as FEC_FIN_ENCUESTA
        ,[NUM_TEL_CONTACTO],[PRI_NOMBRE],[SEG_NOMBRE],[PRI_APELLIDO],[SEG_APELLIDO],[TIP_PARENTESCO]
        ,[TIP_DOCUMENTO],[NUM_DOCUMENTO]
        ,(CASE WHEN (ISDATE([FEC_NACIMIENTO]) > 0) THEN CONVERT(DATE, [FEC_NACIMIENTO]) ELSE CONVERT(DATE, '1900-01-01') END) as FEC_NACIMIENTO
        ,[SEXO_PERSONA],[EDAD_CALCULADA],[IND_GRUPO],[IND_NIVEL]
        ,[EDAD],[NIV_EDUCATIVO],[IND_DISCAP_VER],[IND_DISCAP_OIR],[IND_DISCAP_HABLAR],[IND_DISCAP_MOVERSE],[IND_DISCAP_BAÑARSE]
        ,[IND_DISCAP_SALIR],[IND_DISCAP_ENTENDER],[IND_DISCAP_NINGUNA]
    FROM [dbo].[sisben2]  

/*
 ** Total de registros cargados en la tabla sisteban 6056462
 */
SELECT COUNT(ID_HOGAR_SISBEN_IV) FROM dbo.tblsisben2;    


/*
*** Eliminar tabla Localidad
*/
DROP TABLE dbo.localidadBase;

/*
** Crear tabla sisben2
*/

CREATE Table dbo.localidadBase(
     CONSPERSONA INT NOT NULL
    ,CodigoLocalidad INT
    ,NombreLocalidad NVARCHAR(800)
)

/*
** CREACION LLAVE PRIMARIA
*/
ALTER Table dbo.localidadBase ADD CONSTRAINT pk_id PRIMARY KEY NONCLUSTERED ("CONSPERSONA") NOT ENFORCED;


INSERT INTO dbo.localidadBase
    ([CONSPERSONA]
    ,[CodigoLocalidad]
    ,[NombreLocalidad])
SELECT [CONSPERSONA],[CodigoLocalidad],[NombreLocalidad]
   FROM [dbo].[localidad]

/*
 ** Total de registros cargados en la tabla sisteban 378915
 */
SELECT COUNT(CONSPERSONA) FROM dbo.localidadBase;   
